export declare const apiKey: string;
export declare const city: HTMLElement | null;
export declare const COUNTRY_CODE: HTMLElement | null;
export declare const temp: HTMLElement | null;
export declare const WEATHER_INFO: HTMLElement | null;
export declare const HUMIDITY_INDEX: HTMLElement | null;
export declare const WIND_SPEED_INDEX: HTMLElement | null;
export declare const PRESSURE_INDEX: HTMLElement | null;
export declare const FEELS_LIKE_INDEX: HTMLElement | null;
export declare const VISIBILITY_INDEX: HTMLElement | null;
export declare const SUNRISE_TIME: HTMLElement | null;
export declare const SUNSET_TIME: HTMLElement | null;
export declare const search: HTMLInputElement | null;
export declare const SEARCH_BTN: HTMLButtonElement | null;
export declare const FORECAST_CONTAINER: HTMLCollectionOf<HTMLElement>;
export declare const DAY_WEATHER: NodeListOf<HTMLElement>;
export declare const MAX_TEMPERATURE: NodeListOf<HTMLElement>;
export declare const MIN_TEMPERATURE: NodeListOf<HTMLElement>;
export declare const SUNNY_DAY: string;
export declare const CLOUDY_DAY: string;
export declare const RAINY_DAY: string;
export declare const SNOWY_DAY: string;
export declare const MOON_NIGHT: string;
export declare const CLOUDY_NIGHT: string;
export declare const RAINY_NIGHT: string;
export declare const SNOWY_NIGHT: string;
export declare const days: string[];
export declare let currentWeatherData: any;
//# sourceMappingURL=variables.d.ts.map